# Generated by Django 5.1.1 on 2024-10-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminmaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adminid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('useraddress', models.CharField(max_length=50)),
                ('userphone', models.CharField(max_length=10)),
                ('useremail', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='eventdetails',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=30)),
                ('eventdesc', models.CharField(max_length=50)),
                ('eventprice', models.IntegerField(default=None)),
                ('eventqty', models.IntegerField(default=None)),
                ('eventimage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ordermaster',
            fields=[
                ('ordereventid', models.AutoField(primary_key=True, serialize=False)),
                ('dateoforderevent', models.DateField(auto_now=True)),
                ('ordereventstatus', models.CharField(max_length=30)),
                ('eventquantity', models.IntegerField(default=None)),
                ('eid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.eventdetails')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
    ]
